config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  post "/result" => "homes#result"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insurance_fee.rb
class InsuranceFee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def result
    @face_value_y = params[:face_value].to_i
    face_value_m = (@face_value_y / 12).floor

    # 厚生年金保険料、健康保険料
    if face_value_m >= 635000
      @standard_reward_bymonth_wp = InsuranceFee.where("first_range >= 635000").first.standard_reward_bymonth
      @standard_reward_bymonth_hi = InsuranceFee.where("first_range <= ?", face_value_m).last.standard_reward_bymonth
    else
      @standard_reward_bymonth_hi = InsuranceFee.where("first_range <= ?", face_value_m).last.standard_reward_bymonth
      @standard_reward_bymonth_wp = InsuranceFee.where("first_range <= ?", face_value_m).last.standard_reward_bymonth
    end
    @welfare_pension = (@standard_reward_bymonth_wp * 18.3 / 100 / 2 * 12).floor
    @helth_insurance = (@standard_reward_bymonth_hi * 9.84 / 100 / 2 * 12).floor

    # 介護保険料
    age_range = params[:age_range]
    @standard_reward_bymonth_ni = 0
    @nursing_insurance = 0
    if age_range == "40_to_65"
      @standard_reward_bymonth_ni = InsuranceFee.where("first_range <= ?", face_value_m).last.standard_reward_bymonth
      @nursing_insurance = (@standard_reward_bymonth_ni * 1.8 / 100 / 2 * 12).floor
    elsif age_range == "and_over_65"
      @nursing_insurance = 6014 * 12
      flash[:notice] = "※介護保険料は前年の所得や市区町村ごとに変化します。全国平均の6014円/月で計算しています。"
    end

    # 雇用保険料
    profession = params[:profession]
    if profession == "general"
      @employment_insurance = (face_value_m * 3 / 1000 * 12).floor
    elsif (profession == "agriculture") or (profession == "construction")
      @employment_insurance = (face_value_m * 4 / 1000 * 12).floor
    end

    # 給与所得控除
    if @face_value_y <= 1625000
      @face_value_deduction = 550000
    elsif (1625001..1800000) === @face_value_y
      @face_value_deduction = (@face_value_y * 0.4 - 100000).floor
    elsif (1800001..3600000) === @face_value_y
      @face_value_deduction = (@face_value_y * 0.3 + 80000).floor
    elsif (3600001..6600000) === @face_value_y
      @face_value_deduction = (@face_value_y * 0.2 + 440000).floor
    elsif (6600001..8500000) === @face_value_y
      @face_value_deduction = (@face_value_y * 0.1 + 1100000).floor
    elsif 8500001 < @face_value_y
      @face_value_deduction = 1950000
    end

    # 給与所得(給与収入ー給与所得控除)
    @employment_income = @face_value_y - @face_value_deduction

    # 社会保険料控除
    @social_insurance_deduction = @welfare_pension + @helth_insurance + @nursing_insurance + @employment_insurance

    # 基礎控除
    if @face_value_y <= 24000000
      @basic_deduction = 480000
    elsif (24000001..24500000) === @face_value_y
      @basic_deduction = 320000
    elsif (24500001..25000000) === @face_value_y
      @basic_deduction = 160000
    elsif 25000000 < @face_value_y
      @basic_deduction = 0
    end

    # 所得控除(社会保険料控除＋基礎控除)
    @income_deduction = @social_insurance_deduction + @basic_deduction

    # 課税所得(給与所得ー所得控除)　1000円未満切捨て
    @taxable_income = (@employment_income - @income_deduction).floor(-3)

    # 所得税
    if (1000...1950000) === @taxable_income
      income_tax = @taxable_income * 0.05
    elsif (1950000...3300000) === @taxable_income
      income_tax = @taxable_income * 0.1 - 97500
    elsif (3300000...6950000) === @taxable_income
      income_tax = @taxable_income * 0.2 - 427500
    elsif (6950000...9000000) === @taxable_income
      income_tax = @taxable_income * 0.23 - 636000
    elsif (9000000...18000000) === @taxable_income
      income_tax = @taxable_income * 0.33 - 1536000
    elsif (18000000...40000000) === @taxable_income
      income_tax = @taxable_income * 0.4 - 2796000
    elsif 40000000 <= @taxable_income
      income_tax = @taxable_income * 0.45 - 4796000
    end

    @income_tax = income_tax.to_i.floor

    # 復興特別所得税
    @extra_income_tax = (@income_tax * 0.021).floor

    # 合計納付額(所得税＋復興特別所得税) 100円未満切捨て
    @total_tax = (@income_tax + @extra_income_tax).floor(-2)

    # 手取り額
    @net_income = @face_value_y - @social_insurance_deduction - @total_tax

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/result.html.erb
<div class="container">
  <h2 class="result">手取り額は <span><%= @net_income.to_s(:delimited) %></span> 円です</h2>

  <div class="detail">
    <div>・詳細</div>
    <%= "給与収入(額面)：#{@face_value_y.to_s(:delimited)}円/年" %><br>
    <%= "社会保険料：#{@social_insurance_deduction.to_s(:delimited)}円/年" %><br>
    <%= "所得税・復興特別所得税：#{@total_tax}円/年" %><br>
    <%= "手取り額(給与収入ー社会保険料ー所得税・復興特別所得税)：#{@net_income.to_s(:delimited)}円/年" %><br>

    <!--<%= "給与所得控除：#{@face_value_deduction.to_s(:delimited)}円" %><br>-->
    <!--<%= "給与所得(給与収入ー給与所得控除)：#{@employment_income.to_s(:delimited)}円" %><br>-->
    <!--<div>所得控除</div>-->
    <!--<%= "社会保険料控除：#{@social_insurance_deduction.to_s(:delimited)}円" %><br>-->
    <!--<%= "基礎控除：#{@basic_deduction.to_s(:delimited)}円" %><br>-->
    <!--<%= "所得控除(社会保険料控除＋基礎控除)：#{@income_deduction.to_s(:delimited)}円" %><br>-->
    <!--<%= "課税所得(給与所得ー所得控除)：#{@taxable_income.to_s(:delimited)}円" %><br>-->
  </div>

  <div class="tax">
    <div>・所得税内訳</div>
    <%= "所得税：#{@income_tax.to_s(:delimited)}円/年" %><br>
    <%= "復興特別所得税：#{@extra_income_tax}円/年" %><br>
  </div>

  <div class="insurance">
    <div>・社会保険料内訳</div>
    <!--<%= "厚生年金保険料の標準報酬月額：#{@standard_reward_bymonth_wp.to_s(:delimited)}円" %><br>-->
    <!--<%= "健康保険料の標準報酬月額：#{@standard_reward_bymonth_hi.to_s(:delimited)}円" %><br>-->
    <!--<%= "介護保険料の標準報酬月額：#{@standard_reward_bymonth_ni.to_s(:delimited)}円" %><br>-->

    <%= "厚生年金保険料：#{@welfare_pension.to_s(:delimited)}円/年" %><br>
    <%= "健康保険料：#{@helth_insurance.to_s(:delimited)}円/年" %><br>
    <%= "介護保険料：#{@nursing_insurance.to_s(:delimited)}円/年" %><br>
    <%= "雇用保険料：#{@employment_insurance.to_s(:delimited)}円/年" %><br>
  </div>

  <div class="caution">
    <p>※住民税を計算に含んでいないので、実際の手取り金額は住民税を引いたものとなります。</p>
    <p>※社会保険料控除と基礎控除以外考慮していないので実際の金額と異なることがあります。</p>
    <span><%= flash[:notice] %></span>
  </div>
</div>

app/views/homes/top.html.erb
<div class=container>
  <h1 class="title">手取りチェッカー</h1>
  <div class="overview">
    額面金額から手取りを計算できます。<br>
    額面金額を入力し、年齢と職種を選択してください。
  </div>
  <div class="caution">
    ※令和3年4月1日現在法令等に基づいて算出します。<br>
    ※厚生年金保険料、健康保険料、介護保険料は東京の保険料額表を元に算出しております。
  </div>
  <div class="form">
    <%= form_with url: result_path, local: true do |f| %>
    <%= f.number_field :face_value %>
    <%= f.select :age_range, [["40歳未満", "under_40"], ["40歳以上65歳未満", "40_to_65"], ["65歳以上", "and_over_65"]] %>
    <%= f.select :profession, [["一般", "general"], ["農林水産・清酒製造", "agriculture"], ["建設", "construction"]] %>
    <%= f.submit "調べる" %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncomeChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>